DEFINES+=PROJECT_CONF_H=\"project-conf.h\"
DEFINES+=ATTRIBUTE_H=\"attribute.h\"
CONTIKI_PROJECT = trace
APPS+=powertrace
all: $(CONTIKI_PROJECT)

CONTIKI_WITH_RIME = 1

CONTIKI = ../..
include $(CONTIKI)/Makefile.include
